project:
  type: website
  output-dir: docs

website:
  title: "Maia Sosa Kapur" 
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: posts.qmd
        text: Blog Posts
      - publications.qmd
      - href: https://scholar.google.com/citations?user=H6AeRamFmxUC&hl=en
        text: Google Scholar

format:
  html:
    theme: solar
    css: styles.css
    toc: true



