project:
  type: website
  output-dir: docs

website:
  title: "Maia Sosa Kapur" 
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: posts.qmd
        text: Blog Posts
      - href: media.qmd
        text: Media & Talks
      - publications.qmd
      - href: https://scholar.google.com/citations?hl=en&user=5OsRPbgAAAAJ&view_op=list_works&sortby=pubdate
        text: Google Scholar


format:
  html:
    theme: solar
    css: styles.css
    toc: true



