---
title: "Management Science"
editor: source
---
You can find an up-to-date list of my peer-reviewed publications on [Google Scholar](https://scholar.google.com/citations?user=5OsRPbgAAAAJ&hl=en). 

Because much of my work directly informs the management of industrial fisheries in the United States and international waters, a large body of my research is contained in grey literature: technical memoranda and formal stock assessment reports submitted to regional fishery management organizations. A list of these publications, and links (where available), is provided below.

**Stock Assessments Used for Fisheries Management**

1.	Spies, I., Kapur, M., Barbeaux, S., Haltuch, M., Hulson, P., Ortiz, I., Spencer, L., and Lowe, S. Assessment of the Pacific Cod stock in the Aleutian Islands. North Pacific Fishery Management Council, 2024. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2024/AIpcod.pdf 

2.	Kapur, M. Assessment of the Flathead Sole Stock in the Gulf of Alaska. North Pacific Fishery Management Council, 2024. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2024/GOAflathead.pdf 

3.	Kapur, M. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. North Pacific Fishery Management Council, 2024. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2024/BSAIflathead.pdf 

4.	Kapur, M., Hulson, P. and Williams, B. Assessment of the Pacific Ocean Perch Stock in the Gulf of Alaska. North Pacific Fishery Management Council, 2023. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2023/GOApop.pdf 

5.	Kapur, M. Assessment of the Flathead Sole Stock in the Gulf of Alaska. North Pacific Fishery Management Council, 2023. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2023/GOAflathead.pdf 

6.	Kapur, M. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. North Pacific Fishery Management Council, 2023. https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2023/BSAIflathead.pdf 

7.	Kapur, M. and Monnahan, C. Assessment of the Flathead Sole Stock in the Gulf of Alaska. North Pacific Fishery Management Council, 2022. https://apps-afsc.fisheries.noaa.gov/Plan_Team/2022/GOAflathead.pdf 

8.	Kapur, M. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. North Pacific Fishery Management Council, 2022. https://apps-afsc.fisheries.noaa.gov/Plan_Team/2022/BSAIflathead.pdf 

9.	Kapur, M. Assessment of the Flathead Sole Stock in the Gulf of Alaska. North Pacific Fishery Management Council, 2021. https://apps-afsc.fisheries.noaa.gov/Plan_Team/2021/GOAflathead.pdf

10.	Kapur, M. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. North Pacific Fishery Management Council, 2021. https://apps-afsc.fisheries.noaa.gov/Plan_Team/2021/BSAIflathead.pdf

11.	Kapur, M., Lee, Q., Haltuch, M., Gertserva, V., and Hamel, O. Status update of the U.S. sablefish stock in 2021. Pacific Fisheries Management Council, 7700 Ambassador Place NE, Suite 200, Portland, OR. https://www.pcouncil.org/documents/2021/06/g-5-attachment-5-draft-status-of-sablefish-anoplopoma-fimbria-along-the-us-west-coast-in-2021-electronic-only.pdf/ 108 p.

12.	Haltuch, M., Johnson, K., Tolimieri, N, Kapur, M., and Castillo-Jordán, C. Status of the sablefish stock in U.S. waters in 2019. Pacific Fisheries Management Council, 7700 Ambassador Place NE, Suite 200, Portland, OR. 398 p. https://www.pcouncil.org/wp-content/uploads/2019/10/sablefish_20191022.pdf

13.	Kapur, M., Hamel, O. Catch-only update for China Rockfish in 2019. 
14.	Adams, G. D., Kapur, M., McQuaw, K., Thurner, S., Hamel, O.S., Stephens, A. & Wetzel, C. R. 2019. Stock Assessment Update: Status of Widow Rockfish (Sebastes entomelas) Along the U.S. West Coast in 2019. Pacific Fishery Management Council, Portland, Oregon. https://www.pcouncil.org/wp-content/uploads/2019/10/2019WidowUpdate_final_clean.pdf

15.	Hamel, O. Kapur, M., Catch-only update for Blackgill Rockfish in 2019.

16.	Kapur, M., Fitchett, M., Yau, A., Carvalho F. 2019. 2018 Benchmark Stock Assessment of Main Hawaiian Islands Kona Crab. NOAA Tech Memo. NMFS-PIFSC-77, 114 p. https://doi.org/10.25923/7wf2-f040  Available at: https://www.fisheries.noaa.gov/resource/document/2018-benchmark-stock-assessment-main-hawaiian-islands-kona-crab 

17.	ISC, 2019 (contributor). 2019 Benchmark stock assessment and future projections for the Western and Central North Pacific striped marlin. Honolulu, Hawaii, USA. Available at: http://isc.fra.go.jp/pdf/ISC19/ISC19_ANNEX11_Stock_Assessment_Report_for_Striped_Marlin.pdf

18.	ISC, 2018 (contributor). Stock Assessment of Shortfin Mako Shark in the North Pacific Ocean Through 2016 (No. ISC/18/ANNEX/15). Yeosu, Republic of Korea. Available at: http://isc.fra.go.jp/pdf/ISC18/ISC_18_ANNEX_15_Shortfin_Mako_Shark_Stock_Assessment_FINAL.pdf 

19.	Langseth, B., Syslo, J., Yau, A., Kapur, M., Brodziak, J., 2018. Stock assessment for the main Hawaiian Islands Deep 7 bottomfish complex in 2018, with catch projections through 2022. NOAA Tech. Memo. NMFS-PIFSC 69, 217. Available at: https://repository.library.noaa.gov/view/noaa/17252

20.	Winker, H., Carvalho, F., Kapur, M., Parker, D., Kerwath, S., 2017. JABBA goes IOTC: Just Another Bayesian Biomass Assessment for Indian Ocean Blue shark and swordfish (No. IOTC-2017-WPB15-INF02). Available at: https://www.iotc.org/sites/default/files/documents/2017/10/IOTC-2017-WPM08-11_Rev_1.pdf



 
**Technical Documents Submitted to Fisheries Management Organizations**

1.	ICES (contributor), 2024. Joint ICES-SEAwise Workshop to Quality Assure Methods to Incorporate Environmental Factors and Quantifying Ecological Considerations in Management Strategy Evaluation Tools (WKEcoMSE). ICES Scientific Reports. https://doi.org/10.17895/ICES.PUB.26661457

2.	Hamel, O., Punt, A.E., Kapur, M. and Maunder, M. 2023. Natural Mortality: Theory, Estimation, and Application in Fishery Stock Assessment Models. U.S. Department of Commerce, NOAA Processed Report NMFSNWFSC-PR-2023-02. https://doi.org/10.25923/xqv2-2g73

3.	Kapur, M., Connors, B., DeVore, J., Fenske, K., Haltuch, M., Key, M. 2021. Transboundary Sablefish Management Strategy Evaluation (MSE) Workshop Report. Pacific Fishery Management Council, Supplemental Informational Report 5. https://www.pcouncil.org/documents/2021/06/supplemental-informational-report-5-council-sponsors-successful-sablefish-management-strategy-evaluation-workshop.pdf/  

4.	Carvalho, F., Kapur, M., Ijima, H. 2019. Comparison between Preliminary Stock Synthesis Models for the 2019 WCNPO Striped Marlin Stock Assessment. http://isc.fra.go.jp/pdf/BILL/ISC19_BILL_2/ISC19_BILLWG2_WP4.pdf

5.	Fenske, K. H., Berger,  A. M., Connors, B., Cope,  J.M., Cox, S. P., Haltuch, M. A., Hanselman, D. H., Kapur, M., Lacko, L., Lunsford , C., Rodgveller, C., and Williams, B. 2019. Report on the 2018 International Sablefish Workshop. U.S. Dep. Commer., NOAA Tech. Memo. NMFS-AFSC-387, 107 p. Available at: https://www.afsc.noaa.gov/Publications/AFSC-TM/NOAA-TM-AFSC-387.pdf 

6.	Sculley, M., Kapur, M., Yau, A., 2018. Size composition for swordfish Xiphias gladius in the Hawaii-based pelagic longline fishery for 1995-2016 (No. WP-18-003). https://doi.org/10.7289/V5/WP-PIFSC-18-003 

7.	Sculley, M., Yau, A., Kapur, M., 2018. Standardization of the swordfish Xiphias gladius catch per unit effort data caught by the Hawaii-based longline fishery from 1994-2016 using generalized linear models. (No. WP-18-001). https://doi.org/10.7289/V5/WP-PIFSC-18-001 

8.	Winker, H., Carvalho, F., Thorson, J.T., Kapur, M., Parker, D., Kerwath, S., Booth, A.J., Kell, L., 2017. Performance evaluation of JABBA-Select against an age-structured simulator and estimation model (No. MARAM/IWS/2017/Linefish/P3 Performance). Cape Town, South Africa. Available at: https://drupalupload.uct.ac.za/maram/Documents/pub/2017/IWS 2017/MARAM_IWS_2017_Linefish_P3.pdf 

9.	Winker, H., Carvalho, F., Thorson, J.T., Kapur, M., Parker, D., Kerwath, S., Booth, A.J., Kell, L., 2017. JABBA-Select: an alternative surplus production model to account for changes in selectivity and relative mortality from multiple fisheries (No. MARAM/IWS/2017/Linefish/P2). Cape Town, South Africa. Available at: https://drupalupload.uct.ac.za/maram/Documents/pub/2017/IWS 2017/MARAM_IWS_2017_Linefish_P2.pdf 

10.	Kapur, M., Yau, A., 2018. Size Compositions and Sex Ratios of Oceanic Whitetip Sharks and Giant Manta Rays for Longline Fisheries in the Pacific Islands Region (DR-18-012). Honolulu, HI. https://doi.org/10.25923/67hf-bn93

11.	Kapur, M., Brodziak, J.A., Fletcher, E.J., Yau, A.J., 2017. Summary of Life History and Stock Assessment Results for Pacific Blue Marlin, Western and Central North Pacific Striped Marlin, and North Pacific Swordfish. (No. WP-17-004). 10.7289/V5/WP-PIFSC-17-004 Available at: http://www.pifsc.noaa.gov/library/pubs/WP-17-004.pdf

12.	Sculley, M.S., Brodziak, J.A., Yau, A.J., Kapur, M., 2017. An Exploratory Analysis of Trends in Swordfish (Xiphias gladius) Length Composition Data from the Hawaiian Longline Fishery (No. WP-17-002). 10.7289/V5/WP-PIFSC-17-002. Available at: https://repository.library.noaa.gov/view/noaa/14862/noaa_14862_DS1.pdf

