---
title: How I studied for my PhD General Exam
author: ~
date: '2020-06-05'
slug: how-studied-general
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-06-05T15:36:27-07:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
I am finally a PhD Candidate! You may want to check out my ["How I studied for my PhD Quals"](https://maiakapur.netlify.app/post/quals/how-studied-quals) post, which detailed my prep for a 5-day written examination I took in December. The General exam in my program is more about investigating 1) your preparedness and thinking regarding your proposed dissertation project, and 2) any gaps in your knowledge that should be addressed between now and your defense. This latter point was fairly disconcerting for me, as it's hard to know if you're doing well on a test designed to expose your shortcomings. Also, unlike the Qualifying exam, the format is an all-in-one, three-hour oral bonanza where there is no way to ~~scream into a paper bag~~ take breaks/regroup after a particularly hard question. In any case, I passed, so here are some tips that can hopefully be generalizable to others taking exams in a similar format. I've split these into prep tips and in-the-moment advice.

# In Preparation <br>
1. **Simplify the guessing game**. Studying for this exam is a little harder because your committee may not give you any readings or additional topics to read about, leaving you to think you should know the entirety of your scientific field. Rather, your #1 priority should be to demonstrate you grasp the *essential concepts, assumptions and methods* YOU will use in your disseration work, and have a notion of how your results will *fit into the literature at large*. For that reason, I spent about 85% of my time making my proposal presentation clear and thorough, and prepared for questions like "How do you expect X to play into your results?", "Have you considered using Y method?", and "How is this different from work by Z?". You'll notice these are *open ended* and designed to check that you aren't just following a recipe for your study.

2. **The 15% basis**  I studied on the unempirical assumption that only 15% of the committee's confidence in my ability to complete my project would be based on my ability to respond to technical & conceptual questions about my field. I convinced myself that the *overwhelming factor which will convince them that I'm ready to progress on my dissertation* is, well, the demonstrated progress I've actually made to this point (writing a proposal counts, too!). In other words, the committee ~is not going to~ did not fail me because I [did] get nervous, blank out, or can't perfectly recall a concept in the moment, if I've otherwise demonstrated I can produce research and find answers when I need them. However, there are some "tricks" towards approaching that 15%, which I share in point #3.

3. **The 101 Slide & The "Warrants Future Research"**. I recognized that the questions people fear getting -- the sudden-death, "gotcha" questions regarding a specific paper/equation/idea in your field, are less terrifying if you think of them the way the faculty think of them.  I find such questions invariably fall into one of two categories. 
    a. The first I call the "**101 Slide**". These are questions about basic concepts in your field which a 101 (introductory) course may have dedicated a lecture or lab exercise to -- and that is the degree of response they are looking for! A classic my adviser throws around is, "How do you get the highest fishing yield from a cohort?". Your brain will instantly rat-wheel around all the things that could lead one to not know the maximum yield...but the answer, literally, is "fish when the cohort biomass is maximized." Exactly the response that would appear on an undergrad lecture slide! ** Full disclosure: I blanked out on a 101 question ** fairly early in my exam and was pretty sure it was a fatal mistake. Depsite all the knowledge I had about this phenomenon, I still fell prey to the anxiety-brain-wipe...and survived. So you will, too `r emo::ji('smile')` 

    b.  "**Warrants future research**" are questions likely to appear in the discussion part of (the faculty's) recent papers, and they are not expecting you to have a definitive answer. Questions beginning with "have you thought about..." or "what is the possibility..." are hints that the topic falls into this category and they're asking you to spectulate. **When in doubt, it looks good to start mentioning extant work on that topic**; the faculty may guide you towards which paper(s) they felt were conclusive, or be satisfied to know that you are aware it is an area of ongoing research. A strong response would suggest what experiments could be done to reduce speculation.
    
The trick, obviously, regarding point 3 is knowing which category the question falls into given the topic. You should be generally familiar with open research questions in your field, emphasizing those *related directly to your project* and *pet interests of your faculty members*. For example, my disseration doesn't do a lot of environmental modeling explicitly, but I am aware that there is an open debate regarding the influence of climate (environment) vs biomass on determining recruitment. I can name the folks involved in this work and what their general findings have been, and some of the challenges to implementing such research in our own context.

# In the Moment
Here are some pointers -- but know that nothing can calm you down come exam day like knowing you have put in the right amount of preparation.

+ In my adviser's words: "Don't be chaotic". This means don't panic. Repeat the question back once asked to buy yourself some time. 
+ Any amount of silence feels way longer to you than it does to them. It looks better to pause and choose your words carefully than to ramble and hope you step on a right-answer mine.
+ DO NOT overhydrate beforehand. You will need to be abiotic for three hours.
+ Keep in mind you have probably read WAY more papers in depth in the last ~2 months than the faculty. Also keep in mind that while they could readily write down important equations/concepts that they *regularly work with*, they really don't know everything and likely could not perfectly answer every question asked by the others in the room if the roles were reversed. This isn't about being arrogant, it's about being realistic in what actually makes for a succesful scientist. 
+ Assume they want you to pass and move on. Failing looks bad on your advisor, ultimately -- so believe that this is a group that wants to see you suceeed.
+ "I don't know" is a valid response. If you are afraid the question falls into the category of 3a (101 Slide) and you really draw a blank, you could choose to mention how you do/do not think it super relevant to your project, hence giving a bit of cover for perhaps why you didn't review it in depth. Silence is better than rambling here.
