---
title: How I studied for my PhD Quals
author: ~
date: '2020-01-01'
slug: how-studied-quals
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-01-01T15:36:27-07:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
Yay, I got a high pass on my exam (now back to the things I neglected Autumn quarter). Before I disappear, I wanted to share how I went about studying for my exam, in hopes this can help other PhD students. Disclaimer: this is likely UW/SAFS specific, and the exam is a 5-day written format where each committee member gave me a set of readings and/or topics from which I was supposed to prepare to answer any long-format question they could give me in a single day.

+ **Acquire materials early**. I actually got my readings over the summer, well before I knew exactly when I was taking the exam. This gave me a birds-eye view of the magnitude of the readings and helped me triage how much time I'd spend on each. For example, my advisor assigned two textbooks -- I started reading these on the bus so when crunch-time came I was really reading them for the 2nd or 3rd time.
+ **Make a weekly gameplan**. This is extremely valuable. I set my exam date about 2.5 months out, and drew up a timetable of what readings or topics I was to accomplish each week, with the final two weeks dedicated to review.
+ **Have a hardcore paper-organization system**. If you can do this with printed sheets, I'm in awe. Otherwise, especially since I was required to synthesize and cite papers on the fly, I developed three digital tracking regimes for my readings. Three sounds like a lot, but I found using the following method enabled me to read each paper multiple times, extract the valuable information from it, and have pre-written summaries ready to go come exam day. The basic system was this:
    a. **Mendeley** (any bib software should do): Load in all the readings, sorted into folders based on which committee member assigned it. This gives you a gestalt for the topics they're leaning towards. Inside the software, I will read, highlight, and give brief annotations to the text itself. If there are equations or figures, I will paste a comment and summarize what is being said in my own words.
    b. **Excel** (see my <a href = "https://maiakapur.netlify.app/post/how-i-keep-up-with-the-literature/">How I keep up with the Literature</a> post). I continued my table-style tracking, but included a column for keywords that I thought may come up in the exam. For example, one comm. member gave me readings about catch-only methods, MSY, data-poor methods, and global fisheries; each of these became a keyword flag so I could sort the citations quickly depending on the question. Other columns included "claim", "methods", "major takeaways" and "larger scale conclusions", where I connected that paper's findings with others in that subsection.
    c. **Word**. This is where the magic happened. For each committee member, I would make up some generalized questions and try to answer them in a loose, outline style referring to my Excel sheet. I normally did this a day or two after my first Mendeley-Excel pass of the articles, which meant I got to do a second reading of the papers and ensured I understood them enough to comment intelligently. Good questions are things that would open a review paper or Op-Ed, not things like "What did Sekkar et al. say about X?". Synthetic questions, such as "what have we learned about the influence of X on Y" or "Are Z considered good metrics of K?" are fruitful and will allow you to connect the readings.
+ **Go beyond**. One of the best things I did during the exam prep was take a <a href = "https://www.coursera.org/learn/bayesian-statistics"> Coursera (free, online) course in Bayesian statistics</a>. In add'n to the Bayes textbook I was assigned, the course let me get "tutored" in a condensed, low-pressure way AND the quizzes helped me test my knowledge. It wouldn't have been realistic for me to take a formal Bayes class in the stats department this quarter (midterms and all). It's easy to fool yourself that you "get it" after highlighting a textbook (for which the previous steps aren't as applicable), but MOOCs like Coursera enable you to test yourself in real time.
+ **Pace thyself**. I read a quote last fall that said, "you can either contribute to the literature, or keep up with the literature". Some days I would be deep in my Excel-Word mode for 9+ hours, and feel strangely like I hadn't really "accomplished" anything, but this thought must be banished. Firstly, having a foundation in the literature of your field is something you'll always need, and if you don't do it now, you won't have any more time when gainfully employed.