---
title: Some Algebra for Equilibrium Recruitment
author: ~
date: '2020-05-21'
slug: some-rec-algebra
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-05-20T15:36:27-07:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})
```
I often find myself revisiting the various "re-arrangements" of the Beverton-Holt stock-recruitment relationship, particularly when moving between equilibrium quantities. I wanted to centralize some algebra for myself and anyone else who uses this relationship  regularly.

## The Bev-Holt SRR
Let's start with some working definitions.

$$ \begin{flushleft} R_0 \quad virgin, \quad unfished \quad recruitment \\ SBPR_0 \quad virgin, \quad unfished \quad spawner \quad biomass-per-recruit \\ SSB_0 \quad virgin, \quad unfished \quad spawning \quad biomass \\ SBPR_F \quad  \quad biomass-per-recruit \quad at \quad F \neq 0 \\ SSB_F \quad spawning \quad biomass  \quad at \quad F \neq 0 \\ YPR_F \quad yield-per-recruit \quad at \quad F \neq 0 \\ \end{flushleft} $$

First, let's illustrate how one strings these quantities together in an age-structured model *assuming a stock-recruit relationship* to derive equilibrium quantities.

## Yield-per-Recruit quantities at various F
1) Find $SBPR$ and $YPR$ at your $F$ value of interest, and also calculate these values when $F = 0$. This will vary slightly depending on the setup of your model, but in pseudo-math:
$$
YPR = \large \Sigma_a \small Fs_aN_aw_a
$$

Where $N_a$ is a proportional expected number-at-age, $w_a$ is the expected weight-at-age, and $s_a$ is fishery selectivity.
$$
SBPR = \large \Sigma_a \small E_aN_aw_a
$$
Here $E_a$ is some measure of your population's fecundity at age. The resultant $SBPR$ is going to vary with $F$ because $N_a$ will decline faster when $F$ is greater than zero. 

## SRR in terms of SBPR

2a) Look at your  stock-recruitment relationship. $\alpha$ and $\beta$ are parameters of the Beverton-Holt SRR. We also leverage the definition of equilibrium stock spawning biomass as the product of unfished SBPR and REcruitment. You can confirm this makes sense by describing the equation with words: the virgin/unfished spawning biomass is the expected spawning biomass for one virgin/unfished recruit times the number of recruits. The same relationship will apply for equilibrium biomass.

$$ \begin{flushleft}
R_F = \frac{SSB_F}{\alpha + \beta SSB_F} \quad Bev-Holt\\
SSB_0 = SBPR_0 \times R_0 \\
SSB_eq = SBPR_{eq} \times R_{eq} \\
\end{flushleft} $$

2b) Re-arrange the SRR to be in terms of $SBPR$. You will need to pick a number (or estimate) $R_0$. We do this by substitution:
$$ \begin{flushleft}
R_F = \frac{SSB_F}{\alpha + \beta SSB_F} \quad Bev-Holt\\
SSB_{eq} = SBPR_{eq} \times R_{eq} \\
R_{eq} =  \frac{SBPR_{eq} \times R_{eq} }{\alpha + \beta ( SBPR_{eq} \times R_{eq} )} \\
R_{eq}(\alpha + \beta ( SBPR_{eq} \times R_{eq} )) =  SBPR_{eq} \times R_{eq}  \\
\alpha + \beta ( SBPR_{eq} \times R_{eq} ) =  SBPR_{eq}   \\
\beta ( SBPR_{eq} \times R_{eq} ) =  SBPR_{eq} - \alpha  \\
 R_{eq}  = \frac{ SBPR_{eq} - \alpha}{\beta \times SBPR_{eq} }  \\
\end{flushleft} $$

### Alpha & Beta in terms of steepness & recruitment
3) Sweet,  now we need a nice definition for $\alpha$ and $\beta$. Spoiler: these only vary by $R_0$ and steepness, $h$, which is defined as the expected recruitment at 20% of $SSB_0$ (hence the 0.2s). Here's the derivation of those values. Recall that $SSB_0 = SBPR_0 \times R_0$, meaning $SBPR_0$ can be substituted for $\frac{SSB_0}{R_0}$.
Let's start with beta:

$$
\begin{array}
{cc}
R_0 = \frac{SSB_0}{\alpha + \beta SSB_0} & original \\
\alpha + \beta SSB_0 = \frac{SSB_0}{R_0} & rearrange, \quad sub \\
\alpha =SBPR_0 - \beta SSB_0 & alpha \\
hR_0 = \frac{0.2SSB_0}{\alpha + 0.2 \beta SSB_0} & h @ 0.2SSB_0  \\
hR_0 = \frac{0.2SSB_0}{SBPR_0 - \beta SSB_0 + 0.2 \beta SSB_0} & substitute  \\
hR_0 = \frac{0.2SSB_0}{SBPR_0 - 0.8 \beta SSB_0} & simplify \\
hR_0SBPR_0 - 0.8hR_0\beta SSB_0= 0.2SSB_0 & multiply \quad denom\\
hSSB_0 - 0.8hR_0\beta SSB_0= 0.2SSB_0 & sub \quad SSB_0 = \tilde S R_0\\
h - 0.8hR_0\beta = 0.2 & div \quad SSB_0 \\
5h - 4hR_0\beta = 1 & mult \quad 5 \\
\frac{5h-1}{4hR_0} = \beta & solve \quad \beta \\
\end{array}
$$


And now for $\alpha$, starting at the third equation from above:

$$
\begin{array}
{cc}
\alpha =SBPR_0 - \beta SSB_0 & from \quad above \\
\alpha =SBPR_0 -  \frac{5h-1}{4hR_0}SSB_0 & sub \quad \beta \\
\alpha =SBPR_0 -  \frac{5h-1}{4hR_0}SBPR_0 R_0 & sub \quad SSB_0 = SBPR_0 R_0  \\
\alpha =SBPR_0 -  \frac{5h-1}{4h}SBPR_0 & cancel \quad R_0  \\
\alpha =SBPR_0 \langle1-  \frac{5h-1}{4h}\rangle & factor  \\
\alpha = SBPR_0 \langle \frac{1-h}{4h}\rangle & rearrange   \\
\end{array}
$$

## Bonus Round: Stock Synthesis Recruitment Syntax
Ever wonder where the Beverton-Holt syntax in the Stock Synthesis manual comes from? It is simply the substitution & rearrangement of our derived values for $\alpha$ and $\beta$ into the original stock-recruit relationship. The "trick" (not really) is just leaving the equation for $\alpha$ in terms of virigin biomass and recruitment.
$$ 
\begin{flushleft}
R_F = \frac{SSB_F}{\alpha + \beta SSB_F} \quad Bev-Holt\\
R_F = \frac{SSB_F}{\frac{SSB_0}{R_0} \langle \frac{1-h}{4h}\rangle + \frac{5h-1}{4hR_0} SSB_F} \quad substitute\\
R_F = \frac{SSB_F 4hR_0}{SSB_0(  1-h)+ SSB_F(5h-1)} \quad flip \quad denom\\
\end{flushleft} 
$$
## Yield and Surplus Production Curves

4) We are almost done. We have equations for equilibrium recruitment, and the definitions for the parameters of that equation. Note that equilibrium recruitment *will change* with $F$ because $SPBR_F$ changes, whereas alpha and beta will not (this is important later). We can now write down equations for our resultant equilibrium spawning biomass, and equilibrium yields:
$$ 
\begin{flushleft}
SSB_{eq} = R_{eq} \times {SBPR_F} \\
Yield_{eq} = R_{eq} \times {YPR_F}
\end{flushleft} 
$$
The "yield curve" is simply obtained by re-calculating these values across a range of Fs and plotting the results against input $F$ and/or resultant $SSB$. The height of the resultant dome is dependent on the value of $h$ used, and the skewness is related to selectivity. For the yield curve specifically, the peak occurs at the point just before natural mortality eclipses somatic growth, and the descending limb will be more "bendy" if you are selecting fish far before they mature. Another way of saying this is that the descending limb will accordingly change in height depending at the age of first capture.
